### ISSUE TITLE
files like  scene_0183.pth  missing

### ISSUE THREAD

**Issue by kys321** [olivia23333/E3Gen#4]
Thanks for your work. But I have a question while running mode 'transfer',which needs latent_code like 'demo/transfer_exp/scene_0183.pth',how can I obtain these files?

**Comment by olivia23333** [comment]
You can save the latent code for generated avatar by utilizing torch.save in `def eval_and_viz(self, data, decoder, code, viz_dir=None, cfg=dict(), ortho=True, recon=False, return_norm=False):` in`E3Gen/lib/models/autodecoders/base_nerf.py` defined in Line 515. You can also fit latent code to multi-view images while freezing the decoder and diffusion parameter and then save the latent code.

**Comment by kys321** [comment]
GOT it！ tks for your reply.
