### ISSUE TITLE
FileNotFoundError for animate, transfer and edit

### ISSUE THREAD

**Issue by CHMimilanlan** [olivia23333/E3Gen#6]
After I ran command 
`python test.py configs/ssdnerf_avatar_uncond_thuman_conv_16bit.py work_dirs/cache/iter_160000.pth --mode 'animate'`
`python test.py configs/ssdnerf_avatar_uncond_thuman_conv_16bit.py work_dirs/cache/iter_160000.pth --mode 'transfer'`
`python test.py configs/ssdnerf_avatar_uncond_thuman_conv_16bit.py work_dirs/cache/iter_160000.pth --mode 'edit'`

Following error occurred by each:
FileNotFoundError: [Errno 2] No such file or directory: 'demo/ani_exp/ani_file/CMU/06/06_13_stageii.npz'
FileNotFoundError: [Errno 2] No such file or directory: 'demo/transfer_exp/scene_0183.pth'
FileNotFoundError: [Errno 2] No such file or directory: 'demo/edit_exp/scene_0225.pth'

It seemed that no files were provided in code. Meanwhile, after I watching closely to README.md file, there was no website link provided for downloading these files. So could you provide these files? I will be grateful for your timely response!

**Comment by olivia23333** [comment]
The 'demo/ani_exp/ani_file/CMU/06/06_13_stageii.npz' is from AMASS dataset, you can register and download it on your own from https://amass.is.tue.mpg.de 
'demo/transfer_exp/scene_0183.pth' and 'demo/edit_exp/scene_0225.pth' are generated latent codes, I share them with https://drive.google.com/file/d/1EXBueuArrSDpZ95lGd8TOztCYZ_cUSxA/view?usp=share_link. You can download them from this link. If you still meet problems with the `test.py` please feel free to ask.

**Comment by CHMimilanlan** [comment]
thanks！
